import { IoMdJournal } from "react-icons/io";

export const projects = [
  {
    title: '(ONGOING INTERNSHIP) Matching Document ID with Selfies - A project in collaboration with Swiggy',
    description: "The software that is being designed will be able to recognize a person’s face through mapping which is based on their nose, eyes, chin, and cheeks, taking in distinctive qualities making each of us different from one another. The reliability of this software is being tested for its accuracy and security. Selfies of a person will be matched with their respective ID cards and the model will be trained accordingly to enhance the metrics being taken into account",
    image: '/images/swiggy.png',
    tags: ['PyTorch', 'Python', 'scikit-learn'],
    visit: 'https://github.com/HarshithK13/Database-System-for-Hostels-of-Institute',
    id: 0,
  },
  {
    title: '(ONGOING PROJECT) Detection of Thyroid Cancer through Secondary Harmonic Images',
    description: "Thyroid Cancer detection is being tested with the help of its BSHG, FSHG and TPEF images of each patient. The dataset consists of the images related to 292 patients, having either Follicular Adenoma or Follicular Thyroid Carcinoma. A model (as of now, an asymmetric autoencoder) is taken and is encoded on these images which are stacked, then it extracts the latent layer and decodes the data again. This latent layer determines whether there is cancer or not. Experiments are being done regarding the model as of now.",
    image: '/images/thyroid.png',
    tags: ['PyTorch', 'Python', 'scikit-learn'],
    visit: 'https://github.com/HarshithK13/Database-System-for-Hostels-of-Institute',
    id: 1,
  },
  {
    title: 'Efficient Adversarial Attack Generation in Black Box Settings ',
    description: "In this project, we examined how well a trained Resnet-50 model can withstand the Boundary Biased Attack, and how well a defense mechanism known as 'Adversarial Training' functions when this attack that we have implemented attacks it. We also compare the performances of various other attacks with this attack that we have implemented.\n",
      image: '/images/blackbox.png',
      tags: ['PyTorch', 'Python', 'scikit-learn'],
    source: 'https://arxiv.org/pdf/1812.09803.pdf',
    visit: 'https://github.com/HarshithK13/Efficient-Adversarial-Attack-Generation-in-Black-Box-Settings',
    id: 2,
  },
  {
    title: '(ONGOING PROJECT) Attention Based Object Classification for Drone Imagery',
    description:"The motivation is to use attention mechanisms that can help improve the accuracy and efficiency of object classification by focusing on the most relevant parts of the image rather than processing the entire image. The proposed attention-based CNN architecture was adopted and compared comprehensively with the existing networks like VGG16, etc.",
    image: '/images/drone_imagery.png',
    tags: ['PyTorch', 'Python', 'scikit-learn'],
    source: 'https://ieeexplore.ieee.org/document/9589099',
    visit: 'https://github.com/HarshithK13/Attention-Based-Object-Classification-For-Drone-Imagery/blob/main/README.md',
    id: 3,
  },
  {
    title: 'Neural Style Transfer',
    description: "The aim of this project is to deploy neural style transfer on a web server written in Streamlit. We have built a web-based app for Neural Style Transfer based on the model proposed by Perceptual Losses for Real-Time Style Transfer and Super-Resolution Perceptual Losses for Real-Time Style Transfer and Super-Resolution.",
      image: '/images/neuralstyle.png',
      tags: ['PyTorch', 'Python', 'scikit-learn', 'Streamlit'],
    source: 'https://arxiv.org/pdf/1603.08155.pdf',
    visit: 'https://github.com/HarshithK13/Neural-Style-Transfer/tree/main',
    id: 4,
  },
  {
    title: 'Three Model Compression Techniques',
    description: "In this project, we have decided to look at the pros and cons of three common techniques used to compress large models into smaller ones which are Pruning, Quantization and Knowledge distillation.",
    image: '/images/compression.png',
    tags: ['PyTorch', 'Python', 'scikit-learn'],
    source: 'https://xailient.com/blog/4-popular-model-compression-techniques-explained/',
    visit: 'https://github.com/HarshithK13/3-Model-Compression-Techniques',
    id: 5,
  },
  {
    title: 'INTERNSHIP @ IISc \n  Vehicle Simulation at IIT Jodhpur',
    description: "This project aims on creating a marker simulation of people moving from one place to another using different modes of transport in the IIT Jodhpur campus. We have used the tool 'Leaflet' to create this marker simulation i.e., to move each mode of transport from one place to another in the campus via the shortest route possible. Leaflet is an open source Javascript library used to build web mapping applications. A typical use of Leaflet involves binding a Leaflet 'map' element to an HTML element.",
    image: '/images/simulation.png',
    tags: ['Javascript', 'Leaflet'],
    visit: 'https://github.com/HarshithK13/cn-iisc-internship',
    id: 6,
  },
  {
    title: 'Multiplayer NIM AI Game-Engine',
    description: "This project aims to extend the Minimax approach to multiplayer (more than 2 players) games. Minimax cannot be directly applied to multiplayer games, hence a new approach MaxN is introduced which tries to maximize the utility for current player at each layer. Another algorithm i.e. Paranoid algorithm which is based on the paranoid assumption that all other players are collectively playing against the current player hence it kind of transforms the MaxN approach to Minimax, where we treat all other players as a single opponent. ",
    image: '/images/multiplayer.png',
    tags: ['Python'],
    visit: 'https://github.com/HarshithK13/cn-iisc-internship',
    id: 7,
  },
  {
    title: 'Music Genre Classification',
    description: "The aim of this project is to make a classifier that classifies music based on their genres. For this, there are many features of music that have to be taken into consideration like amplitude , frequencies , harmonics and tempo. This classifier can be further extended into a song recommendation system and monitoring the popularity of songs with a classification of different genres they belong to.",
    image: '/images/music.png',
    tags: ['Python', 'Seaborn'],
    visit: 'https://github.com/HarshithK13/Music-Genre-Classification/',
    id: 8,
  },
  {
    title: 'Covid19 Data Visualization',
    description: "This project focuses on creating a Dashboard which shows the visualization of the countries and also shows the number Covid19 cases present in a specific province by clicking on it in the map between any specific interval of dates. It also contains plots showing the rise in the number of cumulative cases present. RShiny has been used as an interface for building this dashboard and Covid19API has been used for the data.",
    image: '/images/map.png',
    tags: ['R', 'Seaborn', 'Leaflet'],
    visit: 'https://github.com/HarshithK13/Covid19-Data-Visualization',
    id: 9,
  },
  {
    title: 'Database System For Hostels of Institute',
    description: "We made a database system for the hostels in an institute on phpMyAdmin. We have written a few SQL queries which show the working of the database in the video (can be found in the github repository by clicking on 'Code' below). We've donr query optimization, generated triggers, and have also performed hashing on the tables present in the database. We've included the following features: -> Maintaining updated list of students in hostels -- includes realtime information on student taking leave from hostel and associated fees & rebates; --> Maintaining updated list of issues associated with a particular room; --> Maintaining details of wardens associated with particular hostels; --> Maintaining student information to include picture and other details; --> Database includes biometric inputs as well - to mark hostel-in and hostel-out times, if a student doesn't return by last in-time and not taken leave, then we ping hostel-caretaker / warden",
    image: '/images/phpmyadmin.png',
    tags: ['phpMyAdmin', 'SQL', 'MongoDB'],
    visit: 'https://github.com/HarshithK13/Database-System-for-Hostels-of-Institute',
    id: 10,
  },
];

export const TimeLineData = [
  { year: 2020, text: 'Completed Grade XII', },
  { year: 2020, text: 'Scored AIR 4499 in JEE Advanced', },
  { year: 2020, text: 'Started my Journey at IIT Jodhpur', },
  { year: 2021, text: '1659 rating in November Challenge 2021 Division 3', },
  { year: 2022, text: '5 stars in C++ Hackerrank', },
  { year: 2022, text: 'Completed a Summer Research Internship at IISc Bangalore', },
  { year: 2023, text: 'Selected as Summer Research Intern at IIT Jodhpur', },
];